// frontend/src/components/EditPhotoModal.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue"

import { updatePhoto } from "../api/client"
import type { Person, Photo } from "../types"

const props = defineProps<{
  open: boolean
  photo: Photo | null
  persons: Person[]
}>()

const emit = defineEmits<{
  close: []
  saved: []
}>()

const title = ref("")
const shotMonth = ref("")
const selectedPersons = ref<number[]>([])
const saving = ref(false)

watch(
  () => props.photo,
  (photo) => {
    if (!photo) {
      title.value = ""
      shotMonth.value = ""
      selectedPersons.value = []
      return
    }

    title.value = photo.title || ""
    shotMonth.value = photo.shot_month || ""
    selectedPersons.value = photo.persons.map((person) => person.id)
  },
  { immediate: true },
)

const selectedPersonNames = computed(() =>
  props.persons
    .filter((person) => selectedPersons.value.includes(person.id))
    .map((person) => person.name),
)

function togglePerson(personId: number) {
  selectedPersons.value = selectedPersons.value.includes(personId)
    ? selectedPersons.value.filter((id) => id !== personId)
    : [...selectedPersons.value, personId]
}

async function saveEdit() {
  if (!props.photo) return

  try {
    saving.value = true
    await updatePhoto(props.photo.id, {
      title: title.value.trim() || null,
      shot_month: shotMonth.value || null,
      person_ids: selectedPersons.value,
    })
    emit("saved")
    emit("close")
  } catch (error) {
    alert(error instanceof Error ? error.message : "保存失败，请稍后再试")
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <div v-if="open && photo" class="modal-mask">
    <div class="modal-panel">
      <div class="modal-header">
        <h2>编辑照片</h2>
        <button class="ghost-btn small-btn" @click="emit('close')">关闭</button>
      </div>

      <img :src="photo.image_url" :alt="photo.title || 'photo'" class="modal-image" />

      <div class="form-block">
        <label class="form-label">照片标题</label>
        <input
          v-model="title"
          class="text-input full-input"
          placeholder="修改照片标题"
        />
      </div>

      <div class="form-block">
        <label class="form-label">拍摄月份</label>
        <input v-model="shotMonth" class="text-input month-input" type="month" />
      </div>

      <div class="form-block">
        <label class="form-label">照片人物</label>
        <div class="checkbox-wrap">
          <label
            v-for="person in persons"
            :key="person.id"
            class="checkbox-tag"
          >
            <input
              type="checkbox"
              :checked="selectedPersons.includes(person.id)"
              @change="togglePerson(person.id)"
            />
            <span>{{ person.name }}</span>
          </label>
        </div>

        <p class="helper-text">
          已选：{{ selectedPersonNames.length > 0 ? selectedPersonNames.join("、") : "未选择" }}
        </p>
      </div>

      <div class="modal-actions">
        <button class="primary-btn" :disabled="saving" @click="saveEdit">
          {{ saving ? "保存中..." : "保存修改" }}
        </button>
        <button class="secondary-btn" :disabled="saving" @click="emit('close')">
          取消
        </button>
      </div>
    </div>
  </div>
</template>

// components/EditPhotoModal.tsx
"use client"

import { useEffect, useMemo, useState } from "react"
import { supabase } from "@/lib/supabase"

type Person = {
  id: number
  name: string
}

type PhotoPersonRelation = {
  person_id: number
  persons: {
    id: number
    name: string
  } | null
}

type Photo = {
  id: number
  title: string | null
  image_url: string
  shot_month?: string | null
  photo_persons?: PhotoPersonRelation[]
}

export default function EditPhotoModal({
  open,
  photo,
  persons,
  onClose,
  onSaved,
}: {
  open: boolean
  photo: Photo | null
  persons: Person[]
  onClose: () => void
  onSaved: () => void
}) {
  const [title, setTitle] = useState("")
  const [shotMonth, setShotMonth] = useState("")
  const [selectedPersons, setSelectedPersons] = useState<number[]>([])
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    if (!photo) return
    setTitle(photo.title || "")
    setShotMonth(photo.shot_month || "")
    setSelectedPersons(photo.photo_persons?.map((r) => r.person_id) || [])
  }, [photo])

  const togglePerson = (id: number) => {
    setSelectedPersons((prev) =>
      prev.includes(id) ? prev.filter((pid) => pid !== id) : [...prev, id]
    )
  }

  const selectedPersonNames = useMemo(() => {
    return persons
      .filter((p) => selectedPersons.includes(p.id))
      .map((p) => p.name)
  }, [persons, selectedPersons])

  const handleSave = async () => {
    if (!photo) return

    try {
      setSaving(true)

      const { error: updateError } = await supabase
        .from("photos")
        .update({
          title: title.trim() || null,
          shot_month: shotMonth || null,
        })
        .eq("id", photo.id)

      if (updateError) {
        console.log(updateError)
        alert("更新照片失败")
        return
      }

      await supabase.from("photo_persons").delete().eq("photo_id", photo.id)

      const relations = selectedPersons.map((personId) => ({
        photo_id: photo.id,
        person_id: personId,
      }))

      if (relations.length > 0) {
        const { error } = await supabase.from("photo_persons").insert(relations)
        if (error) {
          console.log(error)
          alert("更新人物失败")
          return
        }
      }

      onSaved()
      onClose()
    } finally {
      setSaving(false)
    }
  }

  if (!open || !photo) return null

  return (
    <div className="modal-mask">
      <div className="modal-panel">
        <div className="modal-header">
          <h2>编辑照片</h2>
          <button className="ghost-btn small-btn" onClick={onClose}>
            关闭
          </button>
        </div>

        <img src={photo.image_url} alt="" className="modal-image" />

        <div className="form-block">
          <label className="form-label">照片标题</label>
          <input
            className="text-input full-input"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
        </div>

        <div className="form-block">
          <label className="form-label">拍摄月份</label>
          <input
            className="text-input month-input"
            type="month"
            value={shotMonth}
            onChange={(e) => setShotMonth(e.target.value)}
          />
        </div>

        <div className="form-block">
          <label className="form-label">照片人物</label>
          <div className="checkbox-wrap">
            {persons.map((p) => (
              <label key={p.id} className="checkbox-tag">
                <input
                  type="checkbox"
                  checked={selectedPersons.includes(p.id)}
                  onChange={() => togglePerson(p.id)}
                />
                <span>{p.name}</span>
              </label>
            ))}
          </div>
          <p className="helper-text">
            已选：{selectedPersonNames.length ? selectedPersonNames.join("、") : "未选择"}
          </p>
        </div>

        <div className="modal-actions">
          <button className="primary-btn" onClick={handleSave} disabled={saving}>
            {saving ? "保存中..." : "保存修改"}
          </button>
          <button className="secondary-btn" onClick={onClose}>
            取消
          </button>
        </div>
      </div>
    </div>
  )
}
